# This is an example mkfile

multi=a b c
obj=U=o
src=U=c
qu=Q
aux=aux

<$aux

$multi: d e f
    echo $prereq

%.$obj: %.$src
    echo $stem

quiet:$qu: d
	echo quiet target

world:V: a.o
	echo making the world.

cmp:Pcmp -s: d e
	echo $prereq

(h|i|j):R: \1\1
	touch $stem1
